package io.valandur.webapi.hook;

public enum HookEventType {
  ALL,
  CUSTOM_COMMAND,
  CHAT, COMMAND,
  PLAYER_JOIN, PLAYER_LEAVE, PLAYER_DEATH, PLAYER_KICK, PLAYER_BAN,
  WORLD_SAVE, WORLD_LOAD, WORLD_UNLOAD,
  SERVER_START, SERVER_STOP,
}
